AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  login-api-lambda.x

  Sample SAM Template for login-api-lambda.x
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LoginFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: login-lambda
      Handler: app.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /health
            Method: get
        Register:
          Type: Api
          Properties:
            Path: /register
            Method: post
        Verify:
          Type: Api 
          Properties:
            Path: /verify
            Method: post
